#!/bin/sh

# Script for deploying

V=false
DRY_RUN=false
while getopts 'vd' OPTION
do
	case $OPTION in
		v)	V=true
					;;
		d)	DRY_RUN=true
					;;
		?)	printf "Usage: %s: [-v] [-d] task_name" $(basename $0) >&2
					exit 2
					;;
	esac
done
shift $(($OPTIND - 1))

if [ $# -ne 1 ]; then
	printf "Usage: %s: [-v] [-d] task_name" $(basename $0) >&2
	exit 2;
fi

# CWD is just current directory
CWD="$(pwd)"

TASK_NAME=$1
TASK_DIR=$1
if [ ! -d $TASK_CWD]; then
	echo "Task directory '$TASK_DIR' not found!" 
	exit 1;
fi

if $DRY_RUN ; then
	echo
	echo "-- THIS IS A DRY-RUN --"
	echo
fi

echo "Deploying $TASK_NAME ($TASK_DIR) ..."
echo


pushd $CWD> /dev/null

# source all scripts in task directory
for f in $TASK_DIR/*.sh
do
	if $V ; then
		echo "Sourcing $f ..."
	fi
	. $f
	if $V ; then
		echo "End sourcing $f ..."
		echo
	fi
done

popd $CWD> /dev/null

echo
echo "Deploy of $TASK_NAME complete!"

if $DRY_RUN ; then
	echo
	echo "-- THIS WAS A DRY-RUN --"
fi
